config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/home", to: "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/contact", to: "static_pages#contact"

    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    resources :users

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze

  before_save :downcase_email

  validates :name,  presence: true, length: {maximum: Settings.char_50}
  validates :email, presence: true,
                    length: {maximum: Settings.char_255},
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: true
  validates :password, presence: true, length: {minimum: Settings.char_6}

  has_secure_password

  # Returns the hash digest of the given string.
  def self.digest string
    cost = if ActiveModel::SecurePassword.min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_column(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated? remember_token
    return false unless remember_digest

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_column(:remember_digest, nil)
  end

  private
  def downcase_email
    email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  before_action :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    {locale: I18n.locale}
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    return unless logged_in?

    redirect_to root_url
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      user_authenticated user
    else
      flash.now[:danger] = t("custom_errors.invalid_login_msg")
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def contact; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.new
    render :new
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find_by id: params[:id]
    return if @user

    render :not_found_404
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = t("pages.welcome_msg")
      redirect_to @user
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name,
                                 :email,
                                 :password,
                                 :password_confirmation)
  end

  def not_found_404; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t("pages.base_title")
    page_title.empty? ? base_title : "#{page_title} | #{base_title}"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user&.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    current_user.present?
  end

  def user_authenticated user
    log_in user
    params[:session][:remember_me] == "1" ? remember(user) : forget(user)
    redirect_to user
  end

  def forget user
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def get_request_path_without_locale
    return request.path if params[:locale].nil?

    path = request.path.split("/")
    path = path.reject{|e| I18n.available_locales.include? e.to_sym}
    path.join("/")
  end

  def add_locale_to_request_path locale = ""
    # remove current locale and return a current path with new locale inserted
    locale.to_s.prepend("/").concat(get_request_path_without_locale)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for user, size: 80
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_base_url = "https://secure.gravatar.com/avatar/"
    gravatar_url = gravatar_base_url + "#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_error_messages.html.erb
<% if @user.errors.any? %>
  <%= t("partial.error_msg_html", user_error_count: pluralize(@user.errors.count, t("label.error"))) %>
<% end %>

app/views/layouts/_error_msg_line.html.erb
<% if @user.errors.full_messages_for(field_opt).any? %>
  <% @user.errors.full_messages_for(field_opt).each do |msg| %>
    <p class="error_msg_line">
      <%= msg %>
    </p>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <%= t("pages.footer_info_html") %>
  <nav>
    <ul>
      <li><%= link_to t("pages.contact.page_title"), contact_path %></li>
      <li><%= link_to t("pages.news.page_title"), t("pages.news.page_url") %></li>
      <li><%= Time.now.strftime("%d/%m/%Y") %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("nav.logo"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("nav.home"), home_path %></li>
        <li><%= link_to t("nav.help"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("nav.logged_in.users"), "#" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t("nav.logged_in.account") %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t("nav.logged_in.profile"), current_user %></li>
              <li><%= link_to t("nav.logged_in.settings"), "#" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("nav.logged_in.logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("nav.login"), login_path %></li>
        <% end %>
        <li><%= link_to t("nav.locale_opts.eng"), add_locale_to_request_path(:en) %>
        <li><%= link_to t("nav.locale_opts.vi"), add_locale_to_request_path(:vi) %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title yield :title %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
  <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css" rel="stylesheet">
</head>

<body>
  <%= render "layouts/header" %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/static_pages/contact.html.erb
<% provide :title, t("pages.contact.page_title")%>

<div class="center jumbotron">
  <h1><%= t("pages.contact.h1") %></h1>
  <%= t("pages.contact.body_html") %>
</div>

app/views/static_pages/help.html.erb
<% provide :title, t("pages.help.page_title")%>

<div class="center jumbotron">
  <h1><%= t("pages.help.h1") %></h1>
  <%= t("pages.help.body_html") %>
</div>

app/views/static_pages/home.html.erb
<% provide :title, t("pages.home.page_title") %>

<div class="center jumbotron">
  <h1><%= t("pages.home.welcome") %></h1>
  <%= t("pages.home.body_html") %>
  <%= link_to t("pages.home.sign_up"), signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/new.html.erb
<% provide(:title, t("pages.signup.page_title")) %>

<h1><%= t("pages.signup.page_title") %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render "layouts/error_messages" %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
      <%= render "layouts/error_msg_line", field_opt: :name %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
      <%= render "layouts/error_msg_line", field_opt: :email %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
      <%= render "layouts/error_msg_line", field_opt: :password %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
      <%= render "layouts/error_msg_line", field_opt: :password_confirmation %>

      <%= f.submit t("pages.signup.signup_button"), class: "btn btn-primary" %>
    <% end %>

    <%= t("pages.signup.opts.already_created_html", login_url: login_path) %>
  </div>
</div>

app/views/users/not_found_404.html.erb
<% provide(:title, t("pages.not_found_404.page_title")) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= t("pages.show_user.not_found_msg_html", {home_url: home_path, signup_url: signup_path}) %>
      </h1>
    </section>
  </aside>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
        <br>
        <%= @user.email %>
      </h1>
    </section>
  </aside>
</div>